<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TaxRadar_backned</RootNamespace>
      <UserSecretsId>8e868cc2-33d2-48d2-908c-76673918812d</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.17.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TaxRadar-Infrastructure\TaxRadar-Infrastructure.csproj" />
    </ItemGroup>

</Project>
