<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TaxRadar_Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.2.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tax-Radar-Domain\Tax-Radar-Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
        <HintPath>C:\Users\Oleh\.dotnet\packs\Microsoft.AspNetCore.App.Ref\10.0.11\ref\net10.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
